### PR TITLE
[BitMex] Bug Fix For Parsing Incoming Bitmex Messages

### PR DESCRIPTION
**Pull request by badgerwithagun**
Updated version of #233

### CODE REVIEW

**Comment by badgerwithagun** [comment]
@dozd, this is a simple change that I can't test (don't use BitMex) but was proposed a long time ago.  I've recreated the PR so we can get it merged.  Would you mind reviewing and merging?

**Comment by jkolobok** [comment]
I can take a look. We use bitmex

**Comment by badgerwithagun** [comment]
@jkolobok - any discoveries?

**Comment by badgerwithagun** [comment]
This PR is being closed as stale. Please re-open if needed.

**Pull request closed without merging**
