### PR TITLE
Added fragmented text message handling in WebSocketClientHandler

### PR DESCRIPTION
**Pull request by Nephtys**
When the received message was fragmented, the first part was sent to the message handler and the rest of the message was ignored. 
The first message has type TextWebSocketFrame and the following have type ContinuationWebSocketFrame. Each frame has a boolean finalFragment to indicate if the message was fully received.
See RFC 6455 section 5.4 and 5.2, and Netty WebSocket08FrameDecoder for more information.

### CODE REVIEW

**Comment by Nephtys** [comment]
Issues mentioning intermittent failures or lost messages may be related

**Comment by badgerwithagun** [comment]
@Nephtys: The change looks sensible. Did you encounter this issue with a specific exchange, or is this just precautionary?

**Comment by Nephtys** [comment]
We encountered this issue with snapshot messages on the LGO exchange websocket, but it's not an exchange specific case, it's how the websocket protocol was designed and any exchange using message framing will encounter this issue.
The resulting errors can be silent because the message is received incomplete, so it can be ignored by the following handlers (in fact, in case of a JSON payload, the JSON will be incomplete, resulting in an exception in the JSON parser and the message never sent to the exchange specific handler (or null). That's why that could be the reason for some other open bugs like "message lost" problems in xchange-stream.
See RFC 6455 section 5.4 and 5.2, and Netty WebSocket08FrameDecoder for more information on how the websocket protocol is built.

**Comment by badgerwithagun** [comment]
All understood; I did read up on this part of the protocol before asking. I'm just wondering which issues this fix might close, since the original reporters might find it interesting. #284 perhaps.  I found it odd that I've never seen it, but I agree; it's probably that it's manifesting in lots of different ways.

In any case, this looks sensible, as I said, so LGTM.

**Comment by davidjirovec** [comment]
Yes, it looks it could help. I am still running my custom xchange-stream bitfinex version with checksums. Still checksum error a few times a day. I'll try changes from this PR, after a few days I can say if it helped.

**Comment by badgerwithagun** [comment]
Thanks @Nephtys and @davidjirovec

**Comment by Nephtys** [comment]
Yes you're right, maybe https://github.com/bitrich-info/xchange-stream/issues/284 and maybe https://github.com/bitrich-info/xchange-stream/issues/183 and https://github.com/bitrich-info/xchange-stream/issues/137

Thank you for your review !

**Comment by davidjirovec** [comment]
Testing, checksum errors still sometimes show up :-|

**Pull request merged**
