### PR TITLE
Interface support for trade service (Implemented for bitmex and okcoin/okex)

### PR DESCRIPTION
**Pull request by declan94**
Add interface support for streaming trade service to get trading order information through WebSocket API.
Implemented the interface for bitmex and okcoin(okex).

### CODE REVIEW

**Comment by henryxwong** [comment]
Anything I can help with this PR? Code review or resolving the conflict?

**Comment by makarid** [comment]
I am waiting for this PR to merge in order to update the StreamingTradeService with getUserTrades implementation.

**Comment by badgerwithagun** [comment]
@declan94 , @makarid , @mdvx: I'm trying to get as many PRs as I can either merged or closed, so we can start working towards merging this library with XChange.  What is the status of this?  Is anyone still waiting for it?  Are we close to being able to merge?

**Comment by badgerwithagun** [comment]
OK guys, I'm going to close this but add a reference to the README to say this PR can be used as a start point if anyone wants to add Bitmex/OKEX private channels in the future.

**Pull request closed without merging**
