### PR TITLE
Generic user channels (balance, open orders, user trades) + support for Binance, Bitfinex, Coinbase Pro

### LINKED ISSUE #274: [WORK IN PROGRESS] Generic authenticated stream API
# Introduction
I intend to create `StreamingTradeService` and `StreamingAccountService` interfaces to accompany `StreamingMarketDataService`, mirroring XChange's core APIs.

These will deliver the following:

* Balance updates
* Authenticated (user) trades
* Order updates/execution reports

This has been a long time coming, but I'm now working on it.  I'll will publish regular PRs to merge work into this repo as I go, status updates here, and fork URLs for anyone that wants to use the work in progress.

Please post here if you have thoughts on the API or implementation approach.

# Approach

PRs #273 (formerly #209), #267, #246 and #244 all have taken different approaches to user-authenticated streams. I am trying to standardise these around the approach of #246 and #273 to follow on from #160, which is:

* [x] If the same socket as the public stream can be "elevated" to an authenticated stream, it should be, rather than opening multiple streams
* [x] xchange-stream will open an authenticated stream (or elevate the public one) if there are API key details provided in the `ExchangeSpecification`
* [x] Supported exchanges will provide a "level 2", exchange-specific API, exposing the raw channel data on public methods.  So, for example, `BinanceStreamingTradeService` will have a `getExecutionReports()` method which returns instances of the execution report data structure in the [binance API](https://github.com/binance-exchange/binance-official-api-docs/blob/master/user-data-stream.md) docs.
* [x] Where possible, the exchanges will support the generic "level 1" APIs detailed below by combining, filtering and transforming the output of their level 2 APIs.
* [x] All data will be provided in a `PublishSubject`-like fashion.  If you're subscribed to the `Observable`, you get the data. If you're not, you don't. Nothing will be buffered.
* [x] I will create new `StreamingTradeService` and `StreamingAccountService` interfaces and move the new methods from `StreamingMarketDataService` to bring the location of these methods in line with XChange.
* [x] The streams contain changes/deltas only
* [x] The streams have no guarantee that updates won't be missed, and no way to tell if they have
Therefore, to use the streams reliably, you should combine these streams with polling to make sure any local snapshots you create are re-synced regularly

# API changes

The following new methods will be created:

| Service | Signature  | Description   | Notes |
|---|---|---|---|
| `StreamingTradeService` |  `Observable<UserTrade> getUserTrades(CurrencyPair currencyPair, Object... args)`  | This will return reports of the user's own trades. | Currently, for Coinbase Pro and Binance, we return these "mixed" with the public trades in `getTrades()`.  This will be changed.  If you need `UserTrade`s mixed with your `Trade`s, just `Observable.merge()` the two streams.  This will be more flexible.  | 
| `StreamingTradeService` | `Observable<Order> getOrderUpdates(CurrencyPair currencyPair, Object... args)`  |  This will return updates to the user's open orders. | If you receive a status indicating that the order has been removed (e.g. `CANCELED`) you should assume you'll get no more updates.  A status of `NEW` will indicate acceptance and appearance on the order book and `PENDING_NEW` will indicate receipt but not confirmation.  | 
| `StreamingAccountService` | `Observable<Balance> getBalanceUpdates(Currency currency, Object... args)`  | This will return updates to the specified currency.  | None |

These will explicitly state that they do not guarantee delivery or sequence (see below for the discussion around this).

# Status

## Level 2 Support

Is already in the mainline.

## Level 1 support

PR #340 has been issued but should be considered ready for merge. I'm conducting some production testing.

### LINKED ISSUE #276: Minor synchronization issues with ConcurrentHashMap
`ConcurrentHashMap` isn't fully correctly used in the code.
Yeah, you will not get `ConcurrentModificationException`, but there's possibility to get other issues like lost updates or `NullPointerException`. Of course, possibility is very low, but non-zero.

Here's examples:

https://github.com/bitrich-info/xchange-stream/blob/3819363226d16b193fe8c91ced11f958921ec1f7/service-netty/src/main/java/info/bitrich/xchangestream/service/netty/NettyStreamingService.java#L309-L311

`containsKey` and `put` are 2 different atomic operations. But the whole operation should be executed atomically. You can use [putIfAbsent](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#putIfAbsent-K-V-) or [computeIfAbsent](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#computeIfAbsent-K-java.util.function.Function-) methods to fix it.

https://github.com/bitrich-info/xchange-stream/blob/3819363226d16b193fe8c91ced11f958921ec1f7/service-netty/src/main/java/info/bitrich/xchangestream/service/netty/NettyStreamingService.java#L319-L322

Can be replaced with something like:

```
if (channels.remove(channelId) != null) {
    sendMessage(getUnsubscribeMessage(channelId)); 
}
```

but `getUnsubscribeMessage` must not use `channels` for fetching value by removed `channelId`.

https://github.com/bitrich-info/xchange-stream/blob/3819363226d16b193fe8c91ced11f958921ec1f7/service-netty/src/main/java/info/bitrich/xchangestream/service/netty/NettyStreamingService.java#L327-L329

Just iterate over [entrySet](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#entrySet--).

Should also check `ConcurrentHashMap` usages in other places.

### LINKED ISSUE #278: Number of nioEventLoopGroup threads keeps on increasing if connection is not succesful
Faced this issue when GDAX kept on trying for re-connection. Older nio threads were not getting shutdown. Thread dump showed more than 100 nioEventLoopGroup thread in Runnable state.
Below are the websocket logs:
2019-01-31 01:00:40,131  INFO nioEventLoopGroup-138-1 WebSocket Client connected!
2019-01-31 01:00:40,131  INFO nioEventLoopGroup-137-1 WebSocket Client connected!
2019-01-31 01:00:40,131  WARN nioEventLoopGroup-137-1 Resubscribing channels
2019-01-31 01:00:40,131  WARN nioEventLoopGroup-138-1 Resubscribing channels
2019-01-31 01:01:18,342  INFO nioEventLoopGroup-135-1 WebSocket Client disconnected!
2019-01-31 01:01:18,342  INFO nioEventLoopGroup-135-1 Reopening websocket because it was closed by the host
2019-01-31 01:01:18,342  INFO nioEventLoopGroup-138-1 WebSocket Client disconnected!
2019-01-31 01:01:18,342  INFO nioEventLoopGroup-138-1 Reopening websocket because it was closed by the host
2019-01-31 01:01:20,545  INFO globalEventExecutor-1-162 Connecting to wss://ws-feed.gdax.com:-1
2019-01-31 01:01:20,547  INFO globalEventExecutor-1-162 Registering GDAXWebSocketClientHandler
2019-01-31 01:01:20,548  INFO globalEventExecutor-1-162 Connecting to wss://ws-feed.gdax.com:-1
2019-01-31 01:01:20,550  INFO globalEventExecutor-1-162 Registering GDAXWebSocketClientHandler
2019-01-31 01:01:21,292  INFO nioEventLoopGroup-139-1 WebSocket Client connected!
2019-01-31 01:01:21,292  WARN nioEventLoopGroup-139-1 Resubscribing channels
2019-01-31 01:01:21,297  INFO nioEventLoopGroup-140-1 WebSocket Client connected!
2019-01-31 01:01:21,297  WARN nioEventLoopGroup-140-1 Resubscribing channels
2019-01-31 01:01:40,083  INFO nioEventLoopGroup-137-1 WebSocket Client disconnected!
2019-01-31 01:01:40,083  INFO nioEventLoopGroup-137-1 Reopening websocket because it was closed by the host
2019-01-31 01:01:40,084  INFO nioEventLoopGroup-140-1 WebSocket Client disconnected!

### LINKED ISSUE #283: Gemini WebSocket disconnect doesn't shutdown nioEventLoopGroup threads
Gemini disconnect doesn't shutdown nioEventLoopGroup threads. When re-connection(disconnect and then connect) is done, two new nioEventLoopGroup threads gets created. This count keeps on increasing because older threads never shutdown.

### PR DESCRIPTION
**Pull request by badgerwithagun**
Resolves #274
Resolves #276
Resolves #278
Resolves #283 

See #274 for full description.

This is ready for merge.  Note there are some TODOs around Coinbase Pro support, but it's useful as it is, so I say LGTM.

### CODE REVIEW

**Comment by nielsdraaisma** [comment]
Looks great, thanks for putting in the effort! Looking forward to extending your work onto some more exchanges once merged in.

**Comment by badgerwithagun** [comment]
@pchertalev any chance of a review on this in return?

**Comment by makarid** [comment]
Great work @badgerwithagun ! Thanks for that. It was much needed.

**Comment by nielsdraaisma** [comment]
> @pchertalev any chance of a review on this in return?

Looks great overall, not too familiar with the netty internals but the public API's are exactly what we need.

**Comment by makarid** [comment]
Will someone please approve this PR in order to work on other exchanges implementation?

**Comment by badgerwithagun** [comment]
Thanks for the review @nielsdraaisma.  We do need am approved committer review too.

@Flemingjp perhaps?

**Comment by badgerwithagun** [comment]
Thanks @garciapd.  Still need a review from an approved committer - GitHub blocks me from merging otherwise.

**Comment by makarid** [comment]
Can i become a review or something in order to help speeding up the process?

**Comment by badgerwithagun** [comment]
@makarid - by all means, perform a revie (more reviews is good), but without signoff from an approver like @Flemingjp or @dozd this can't be merged. I'm not allowed to approve my own stuff.

@dozd perhaps you could step in?

**Comment by Flemingjp** [comment]
@makarid If you review the PR briefly, I'll submit it afterwards

**Comment by makarid** [comment]
@Flemingjp i just review it.

**Comment by badgerwithagun** [comment]
@makarid - as much as I could. I rhave been running this code in production for.many months and it is pretty stable, but I only use a limited number of exchanges.  No guarantees, but it it does seem to be more "correct" based on example Netty code I've read elsewhere which makes me feel more confident.

**Comment by makarid** [comment]
> @makarid - as much as I could. I rhave been running this code in production for.many months and it is pretty stable, but I only use a limited number of exchanges. No guarantees, but it it does seem to be more "correct" based on example Netty code I've read elsewhere which makes me feel more confident.

Thanks a lot for your response @badgerwithagun !

**Pull request merged**
