### PR TITLE
[coinbase-pro] Fix corruption of orderbooks & improve performance

### PR DESCRIPTION
**Pull request by badgerwithagun**
Noticed that I was getting zeros appearing in CBP orderbooks. This turned out to be due to concurrency issues with the use of `HashMap` to store the state.

Also made the `getOrderBook` method support any `Number` type for the max depth.

Finally fixed very high CPU usage caused by multiple format translations.

### CODE REVIEW

**Comment by mdvx** [comment]
Test of this patch passes - will close #424 and #426

**Comment by jkolobok** [comment]
Can you fix "out-of-date" problem?

**Comment by badgerwithagun** [comment]
@mdvx - that code was copied out of XChange. I'll tidy it up.

**Comment by badgerwithagun** [comment]
@jkolobok - this fixes all the issues I've found with the CBP orderbook.

**Comment by badgerwithagun** [comment]
@mdvx - I'm not aware of a way of telling if a `BigDecimal` is equivalent to zero without running it through a number conversion to do so. Since any zeros will be filtered out at line 146 they will only get created in the eden space and immediately cleared out so it's probably efficient enough.

**Comment by mdvx** [comment]
> @mdvx - I'm not aware of a way of telling if a `BigDecimal` is equivalent to zero without running it through a number conversion to do so. Since any zeros will be filtered out at line 146 they will only get created in the eden space and immediately cleared out so it's probably efficient enough.

some of the APIs call (different number of 0 for different exchanges) so save on evaluating the string
"0.000000".equals(newVal) ? return BigDecimal.ZERO : new BigDecimal(newVal);
it only works when the exchange always returns "0.000000" as a fixed string always meaning zero.  But your right, it is just eden space

**Comment by badgerwithagun** [comment]
@dozd

**Comment by badgerwithagun** [comment]
Unfortunately until either @dozd or @Flemingjp review this, I can't merge it, since I wrote it.

**Pull request merged**
