### PR TITLE
Rename projects to avoid clashing with XChange

### LINKED ISSUE #464: All modules need renaming ahead of XChange merge
`service-xxx` should be renamed `xchange-stream-service-xxx`
`xchange-xxx` should be renamed `xchange-stream-xxx`

This will namespace the modules appropriately and avoid clash with existing XChange libraries.

### PR DESCRIPTION
**Pull request by makarid**
Fixes #464

### CODE REVIEW

**Comment by badgerwithagun** [comment]
Thanks @makarid. Like the addition of Google formatting in the PR I just created,I don't want to make this change until just before merging the project into XChange. Otherwise it will cause complicated conflicts with any other open PRs.  So I'm going to leave this one on hold for the minute.

**Comment by makarid** [comment]
Totally understand.

**Comment by TSavo** [comment]
@makarid Any chance we can get this rebased onto the current branch? I realize we're in a bit of a holding pattern at the moment, but I'd like to see this one merged since it affects all future PR's.

**Comment by makarid** [comment]
i will rebased it then.

Στις Τρί, 25 Φεβ 2020 στις 9:26 π.μ., ο/η Travis Savo <
notifications@github.com> έγραψε:

**Comment by makarid** [comment]
Hello again. I will make create a new PR with the changes because i have a lot of conflicts. Will you merge it when i make it or we need to wait something? Thanks

**Comment by badgerwithagun** [comment]
> Hello. I will create a new PR with the changes because i have a lot of conflicts. Will you merge it when i make it or we need to wait something? Thanks

I was really hoping to clear the backlog of almost-finished other PRs before we start this sort of work, but I'm getting the feeling we're just going to have to abandon them.  Can you give it a few more days and I'll try and push through as many of the remaining PRs as I can.

**Comment by badgerwithagun** [comment]
Btw, #462 is the other big sweeping change we need to run before an XChange merge.  I'll re-raise that in the same way after this one is done.

**Comment by makarid** [comment]
Sure no problem. Please let me know when you are ready in order to recreate this PR asap. Thanks

**Comment by TSavo** [comment]
I'm all for moving forward with a clean slate of PR's and moving forward with the merge where we can get a lot more visibility. I've opened #523 and #524 to replace the old PR's for format and rename in the interest of moving the ball down the field since both the rename and the format PRs are now blocked on a nasty merge. I suggest we press the button on one or the other since these now require rebasing, and then I can fix the other one that requires redoing, OR we rebase the existing PRs and get them committed so I can delete mine.

**Comment by makarid** [comment]
So, do i need to close this PR?

**Comment by badgerwithagun** [comment]
That's fine, I'll close it. Thanks for this - I'm just going to go with the more recent one.

**Pull request closed without merging**
