### PR TITLE
Fixing typo for taker_order_id in GDAX web socket transaction message

### PR DESCRIPTION
**Pull request by pranithpr**

### CODE REVIEW

**Comment by dozd** [comment]
Could you please remove all the pom.xml from the commit? Try to rebase on the develop

**Comment by dozd** [comment]
Still not good - a lot of pom.xml is changed the does't need to be in the commit

**Comment by bryantharris** [comment]
I ran into mis-naming issue as part of a larger change to add support for the user channel in gdax.  So I've fixed this issue in that pull request.

If there's some file conflicts it might be easier to pick up this fix as part of accepting my pull request.

**Comment by dozd** [comment]
@bryantharris So you fixed this issue in other PR? I'm closing this one.

**Pull request closed without merging**
