### PR TITLE
Fix gdax disconnect NPE/Bitmex execution reports/bug-fix rollup

### PR DESCRIPTION
**Pull request by badgerwithagun**
This also rolls in a rebased version of #141 which looked related enough to do at the same time.

Also includes:

* "L1" support for execution reports on BitMex.  This is in-line with the approach for GDAX on #160, just missing the L2 support that #160 adds on top.  I'm happy with this - I am implementing Binance on the same basis (L1 support first, then work out how to create L2-generic support which combines GDAX and BitMex under the same API later).  However, I don't use my bot code on BitMex so I can't easily test that it works.
* Bitfinex proxy support
* Various updated dependencies
* Performance improvements (mainly ensuring we re-use `ObjectMapper` instances and use them more efficiently (use `treeToValue()`)
* Fix for non-3-character tickers on Binance
* API support and support on Bitmex for testnet/sandbox - I'll be adding support for GDAX as soon as this is merged.
* Reconnect/connection success events for some exchanges

### CODE REVIEW

**Comment by badgerwithagun** [comment]
My change is just the null checks.  Everything else is from #141.

**Comment by badgerwithagun** [comment]
OK, the changes from #141 are causing me some problems when using the same market data service repeatedly (disconnect/reconnect) since the executor's been shut down.  It's also not waiting for shutdown before signalling completion/  I have a fix coming on this PR but want to test it a bit more.

**Comment by Dima-HAN** [comment]
Hi guys, I have this problem, when due to reconnect it goes to the loop. Can u please advice how can I disconnect auto reconnect or set delay on reconnect like a minute ? Thank you I really appreciate it

**Comment by badgerwithagun** [comment]
@Dima-HAN: that doesn't sound like the issue this is trying to solve.

However, have you tried the snapshot build?

**Comment by Dima-HAN** [comment]
Yes, for example today Bitfinex was down and my application went crazy trying to reconnect throwing Too Many requests exception. I was hoping to set a delay on reconnect or at least disable it and I will reconnect with my own call when needed. 

I use eXchange 4.3.6-SNAPSHOT and exchange-Stream 4.3.3-SNAPSHOT in my pom, I guess that is giving me the latest jars?

**Comment by badgerwithagun** [comment]
@Dima-HAN: this PR won't fix it I'm afraid. I suggest you raise an Issue with the feature request.  It does sound useful - perhaps progressively longer delays (exponential backoff) would make sense here.

**Comment by badgerwithagun** [comment]
Is anyone in a position to approve this?

Trying to sort out my mess of a fork so that I can effectively review other peoples'.

**Comment by badgerwithagun** [comment]
Brought up to date, added fixes.  This is getting increasingly difficult to keep synchronised.

**Comment by Flemingjp** [comment]
Possibility to resolve the conflict and then review this PR?

**Comment by badgerwithagun** [comment]
For sure. Will take a look tomorrow.

**Comment by Flemingjp** [comment]
Will pull, test and review :ok_hand:

**Comment by badgerwithagun** [comment]
Ugh, something's not working. I can't test this properly without all the other PRs :(.

Will try and fix that now

**Comment by badgerwithagun** [comment]
Aha, I think that test failure is intermittent.  Happens if the test is running when BitMex is overloaded. Kicked off again

**Comment by badgerwithagun** [comment]
Just reading back through some of the changes on here that I didn't write (it's the result of three or more combined PRs which became interdependent as they all continued and failed to get merged) there are a few features in here which aren't mentioned in the title:

* "L1" support for execution reports on BitMex.  This is in-line with the approach for GDAX on #160, just missing the L2 support that #160 adds on top.  I'm happy with this - I am implementing Binance on the same basis (L1 support first, then work out how to create L2-generic support which combines GDAX and BitMex under the same API later).  However, I don't use my bot code on BitMex so I can't easily test that it works.
* Bitfinex proxy support
* Various updated dependencies
* Performance improvements (mainly ensuring we re-use `ObjectMapper` instances and use them more efficiently (use `treeToValue()`)
* Fix for non-3-character tickers on Binance
* API support and support on Bitmex for testnet/sandbox - I'll be adding support for GDAX as soon as this is merged.
* Reconnect/connection success events for some exchanges

**Comment by badgerwithagun** [comment]
Broken by the upgrade to 4.3.11. I don't use Bitmex so can't help there.

**Comment by badgerwithagun** [comment]
@declan94: yes, I was thinking doing so might help things along. All the Bitmex stuff here was rolled in as part of other peoples' PRs a long time ago and I wasn't comfortable having a bunch of code here I hadn't tested anyway.

I'm happy to revert the Bitmex changes on this branch (probably tonight, Euro time) leaving us with a clean review, and if you could then create a rebased branch and create a new PR we can go from there.

**Comment by badgerwithagun** [comment]
Right, sorry about the delay. Been busy with other things.  I'm going to try and surgically extract the Bitmex changes now.

**Comment by badgerwithagun** [comment]
OK, I've removed all the Bitmex-specific changes.  These were removed in https://github.com/bitrich-info/xchange-stream/pull/191/commits/55513ffc6483cd3c06f2525d4906b748865b75df.

Hopefully this is good to merge now!  @declan94 , if you could submit your review, I'll fix up anything you spot.

Once that's done, I'll resubmit the Bitmex changes separately for someone who uses BitMex to finish off.

**Comment by Flemingjp** [comment]
@badgerwithagun So this is just GDAX work now?

**Comment by badgerwithagun** [comment]
@Flemingjp : updated list:

Just reading back through some of the changes on here that I didn't write (it's the result of three or more combined PRs which became interdependent as they all continued and failed to get merged) there are a few features in here which aren't mentioned in the title:

* Bitfinex proxy support
* Various updated dependencies
* Performance improvements (mainly ensuring we re-use `ObjectMapper` instances and use them more efficiently (use `treeToValue()`)
* Fix for non-3-character tickers on Binance
* Reconnect/connection success events for some exchanges

**Comment by Flemingjp** [comment]
@badgerwithagun Ready to merge this PR if all is good on your end

**Comment by badgerwithagun** [comment]
@flemingjp yep.

**Pull request merged**
