### PR TITLE
Rename GDAX to Coinbase Pro, bump XChange dependency to 4.3.13

### PR DESCRIPTION
**Pull request by badgerwithagun**
Skipping 4.3.12 since 4.3.13 is already out.

GDAX is completely removed from XChange in 4.3.13.

### CODE REVIEW

**Comment by cschwalm** [comment]
LGTM. We should get this merged ASAP. GDAX API shutdown is in a few days.

**Comment by badgerwithagun** [comment]
You around, @Flemingjp?

**Comment by cschwalm** [comment]
Thank you!

**Comment by Flemingjp** [comment]
@cschwalm no worries. The power of mobile aha :)

**Comment by badgerwithagun** [comment]
Worth a 4.3.13 release?

**Comment by Flemingjp** [comment]
@badgerwithagun I was just about to suggest the same. Are there any PRs that can be merged? @dozd can we get a release going?

**Comment by badgerwithagun** [comment]
@Flemingjp there are a few queued up, but as always, the next XChange is always a week or two around the corner.  Better just to release little and often.

**Comment by patrickjm** [comment]
@Flemingjp @badgerwithagun looks like XChange is at 4.3.15, any news on a maven release?

**Comment by dozd** [comment]
I will make a release on Tuesday.

**Pull request merged**
