### PR TITLE
Remove superfluous retry logic for binance depth subscription

### PR DESCRIPTION
**Pull request by dpisklov**
See bitrich-info/xchange-stream#328 for discussion

### CODE REVIEW

**Comment by badgerwithagun** [comment]
Should this be marked as [WIP], @dpisklov? Most of the retry code is still there.

**Comment by dpisklov** [comment]
@badgerwithagun only the required retry logic is there now :) The block that was causing endless retries at start is gone, I tested and it now starts ticking pretty much immediately

**Comment by dpisklov** [comment]
Main thing changed is the condition from strict == to range which relaxes retries a lot

**Comment by badgerwithagun** [comment]
OK, going to merge this into my app and see how things go for a few days :)

**Comment by dpisklov** [comment]
@badgerwithagun let me know how it goes. If all is well would you be able to cut a new version with this change (and other fixes of course) included?
Cheers

**Comment by badgerwithagun** [comment]
It has managed to keep the BTC/USDT orderbook in sync for most of the afternoon so far. If it's still in sync tomorrow I'll call this a win!

**Comment by badgerwithagun** [comment]
Know what - I've tried subscribing and unsubscribing several times and I don't seem to be able to knock this out of sync.  This looks good.  LGTM.

I can't cut a new version - we need @dozd for that.

**Comment by dozd** [comment]
I will release the new version during the week

**Comment by dpisklov** [comment]
Brilliant - thanks guys!

**Comment by dpisklov** [comment]
@dozd sorry for nudging - any luck with the release?

**Comment by dozd** [comment]
Bad man, bad

**Comment by dozd** [comment]
Guys, I will make a release on Tuesday next week. Right know, I don't have an access to the PC where I have my GPG signature for Maven Central and I don't want to setup all the things here as well.

**Comment by dpisklov** [comment]
Cool - thanks for the update

**Comment by dozd** [comment]
It's released - 4.3.16

**Comment by dpisklov** [comment]
@dozd brilliant - thank you!

**Pull request merged**
