### PR TITLE
#448 Kraken exchange orderbook timestamp parse incorrect - fixed

### PR DESCRIPTION
**Pull request by pchertalev**

### CODE REVIEW

**Comment by pchertalev** [comment]
@Flemingjp  @badgerwithagun  Hi guys, if you have a time, please look at this PR

**Comment by mdvx** [comment]
I just got 
list.get(2) == 1574997843.469115 => Friday, November 29, 2019 3:24:03.469 AM
list.get(2)* 1000 == 1574997843469.115 Friday, November 29, 2019 3:24:03.469 AM + 115ns
list.get(2).longValue() => 1574997843 =>Friday, November 29, 2019 3:24:03 AM

Is this choping of the ms and ns?

https://www.epochconverter.com/

**Comment by badgerwithagun** [comment]
I'll leave that to you two to work out and review once everyone's happy.

**Comment by mdvx** [comment]
Any thoughts @pchertalev?

this is the change I would recommend

private static long timestampToMs(String timestamp) {
        return (long)(new BigDecimal(timestamp).doubleValue() * 1000d);
}

**Comment by pchertalev** [comment]
> Any thoughts @pchertalev?
> 
> this is the change I would recommend
> 
> private static long timestampToMs(String timestamp) {
> return (long)(new BigDecimal(timestamp).doubleValue() * 1000d);
> }

Ah! I have found that  XChange Kraken adaptOrder method supports 13 values long:
    Date timeStamp =
        (String.valueOf(order.getTimestamp()).length() >= 13)
            ? new Date(order.getTimestamp())
            : new Date(order.getTimestamp() * 1000);

So we can pass epoch millis in timstamp.
I don't like doubleValues because there is possible such issues: 
https://stackoverflow.com/questions/7408566/java-double-value-0-01-changes-to-0-009999999999999787
So I used BigDecimal multiply instead:

`   new BigDecimal(list.get(2)).multiply(BIG_DECIMAL_1000).longValue()`

**Comment by badgerwithagun** [comment]
Is this one OK to merge, @mdvx , @pchertalev ?

**Comment by pchertalev** [comment]
I'm author of this PR, so I will be very happy to merge this one :)

**Pull request merged**
