### PR TITLE
Defect: NettyStreamingService.disconnect() method does not shutdown a…

### PR DESCRIPTION
**Pull request by pchertalev**
…ll threads - FIXED

+ FIX NullPointerException on first "partial"

Looks like it is fix of bugs: #145 #35

### CODE REVIEW

**Comment by Flemingjp** [comment]
Recommdation would be to close this PR?

**Comment by badgerwithagun** [comment]
I'm going to try merging this locally to see the differences in place.   WIll report back

**Comment by badgerwithagun** [comment]
OK, so it's a mixed bag.

 - The changes to the *Example.java files should be merged.
 - The change to `BitmexStreamingMarketDataService` is already implemented in #191.  The version in #191 is slightly safer (immutable) but they do the same thing.
 - The changes to `NettyStreamingService` are sensible too, and also again implemented in #191.  However, I'm unsure about the differences.  #191 switches to a 2-thread event loop group and I don't know why (I didn't write it).  There's usually a reason for this stuff.  There's also extra logging in #191.

This is a good PR.  If it's merged before #191 it would be beneficial on its own.  However, it would be a pain to fix up #191 again so it merges, and that would screw up the cleanup proposal I put in #224. 

My preference would be to get  #191 merged first, then follow up with this when we can make a choice about the event group thread count question.

**Comment by Flemingjp** [comment]
Ok, this should be put on hold until we can merge #191

**Comment by pchertalev** [comment]
No problemo. I will resolve conflicts after merge #190

**Pull request closed without merging**
