### PR TITLE
xhange 4.3.4, binance fix, okcoin test fix, NettyStreamingService tuning

### PR DESCRIPTION
**Pull request by trojanflash**

### CODE REVIEW

**Comment by dozd** [comment]
Pls rebase, thx! 👍

**Comment by dozd** [comment]
Part of the problem could be fixed by #156

**Comment by badgerwithagun** [comment]
I've rebased this along with some of my own changes on #191.

Found a few issues so I'm fixing those as I go.

**Comment by dozd** [comment]
Ok will be solved in #191

**Pull request closed without merging**
