### PR TITLE
Added CryptoRealTime - Google project that is using this library

### PR DESCRIPTION
**Pull request by galic1987**
Added my project that is using this library 
Potentially, we could use my running project to check if streams to exchanges work

### CODE REVIEW

**Comment by badgerwithagun** [comment]
Probably one for @dozd.

**Comment by galic1987** [comment]
@dozd qq: why is there a yellow dot next to the pull request with status
**Expected - Waiting for status to be reported** ?

**Comment by dozd** [comment]
@galic1987 which PR? This one is marked as merged

**Comment by davidjirovec** [comment]
Here in the list https://github.com/bitrich-info/xchange-stream/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed

I guess the was some communication issue between CI and Github

**Comment by dozd** [comment]
Yeah, but I think it's ok

**Pull request merged**
