### PR TITLE
Generic WebsocketHealthWatcher thread

### PR DESCRIPTION
**Pull request by firegnome**
Implementation for https://github.com/bitrich-info/xchange-stream/issues/80

Since there is no generic way to find out if the websocket is still healthy, i wrote a method (isWebsocketReconnectRequired) that indicates if the socket needs to be reconnected. I implemented this for poloniex2 and its working for me.

@nodarret I tried my best to integrate your changes from #89 but I would really appreciate it If you could look at my changes.

As @hlbkin mentioned, there is a problem with the orderbooks:

> The only problem I see is that when you reconnect, orderBooks become stale i.e. need to be reconnected and submitted full cycle (GDAX full channel for example or binance).

This problem isn't solved yet but i propose to create a new ticket, since this isn't really caused by this pull request.

### CODE REVIEW

**Comment by hlbkin** [comment]
For Bitfinex, they have explicit messages that state when you need to disconnect (https://bitfinex.readme.io/v2/docs/ws-general). is your pull request == workaround for that? or you have seen disconnects from Bitfinex WITHOUT this explicit message?

**Comment by firegnome** [comment]
@hlbkin There are disconnects WITHOUT this explicit message, for example if you connect to a VPN Network it will drop the connection without message.

**Comment by dozd** [comment]
Hello @firegnome , thank you for the PR. I'll go through it after my return from the vacation. It seems a little bit complicated on the first look so I'd like to understand it more before merging.

The main question is about reusability of the code for other exchanges. Is this the common pattern that will be useful elsewhere?

Second concern is about using `new Thread()` with `Thread.Sleep` in "rx world". Some sort of rx timer or interval would be preferred to keep code consistent.

But both are not crucial.

**Comment by firegnome** [comment]
Hi @dozd 
To your first question: It is designed to be reusable for other exchanges. We had a discussion in #80  and other people confirmed, that this is needed on other exchanges too. 

Thank you for your hint with rx timer i will have a look at this and update the PR.

**Comment by nodarret** [comment]
When I have free time I wil check code. For now im trying speed up makret data #101 or write my own solutnion ;)

**Comment by hleb-albau** [comment]
General case -> start any stream, turn off Internet for 10min, turn on Internet. Application will be zoombied.

**Comment by Flemingjp** [comment]
Is a heartbeat a given endpoint? It seems like an over engineered ping/pong transaction - which has now been implemented properly

**Comment by badgerwithagun** [comment]
Well, the ping/pong now implemented is more so that the exchanges don't disconnect from their end. It doesn't tell us if a connection is up but has "gone quiet" - we're not sending pings, just responding to them.

I've never seen it where a socket is open but the exchange has stopped sending data. I HAVE seen it where we have reconnected but failed to send resubscription messages and the connection just starts cycling up and down.

I suspect this predates the relatively reliable auto reconnection logic, but it's hard to say.

**Comment by badgerwithagun** [comment]
Heads up: I'm going to close this PR this week unless anyone feels strongly otherwise.

**Pull request closed without merging**
